# This sets a blank configuation. See:
#
# https://github.com/mojombo/jekyll/wiki/configuration
#
# For more details about configuring Jekyll.
#
title: "Math en jeans"
exclude:
  - README.md


# gmail

# mathenjeanstech // MathenPullxx


# pingdom

# <script>
# var _prum = [['id', '537368ecabe53df9311ae03e'],
#              ['mark', 'firstbyte', (new Date()).getTime()]];
# (function() {
#     var s = document.getElementsByTagName('script')[0]
#       , p = document.createElement('script');
#     p.async = 'async';
#     p.src = '//rum-static.pingdom.net/prum.min.js';
#     s.parentNode.insertBefore(p, s);
# })();
# </script>